CREATE TABLE fundamental_features(
    date VARCHAR(10) NOT NULL,
    code VARCHAR(10) NOT NULL,
    gross_margin FLOAT,
    operating_margin FLOAT,	
    ebt_margin FLOAT,	
    net_income_margin FLOAT,	
    non_operating_ratio	FLOAT,
    operating_profit DECIMAL,
    ebitda	DECIMAL,
    operating_cash_flow	DECIMAL,
    roa	FLOAT,
    roe	FLOAT,
    revenue_growth FLOAT,
    gross_growth FLOAT,
    operating_growth FLOAT,	
    ent_growth	FLOAT,
    net_incom_growth FLOAT,	
    asset_growth FLOAT,
    book_value_growth FLOAT,
    current_ratio FLOAT,
    quick_ratio	FLOAT,
    asset_turnover FLOAT,
    receivables_turnover FLOAT,
    inventory_turnover	FLOAT,
    fixed_asset_turnover FLOAT,
    free_cash_flow FLOAT
)